theme: jekyll-theme-cayman
title: enso managers GmbH, Berlin
# The following lines must nut be modified according the setup of Github pages:
lsi: false
safe: true
source: https://github.com/enso-managers/home
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
